### ISSUE TITLE
[BUG] - Cannot log to stderr

### ISSUE THREAD

**Issue by fullbl** [jitesoft/docker-lighttpd#5]
**Context**

if you add 
```
server.errorlog = "/dev/stderr"
accesslog.filename = "/dev/stdout"
```
to lighttpd.conf, container will not work

```
Awaiting connection to CGI host
CGI host found, starting lighttpd!
2022-12-10 17:09:30: (configfile.c.1720) opening errorlog '/dev/stderr' failed: Permission denied
2022-12-10 17:09:30: (server.c.1584) Opening errorlog failed. Going down.
```

**Description**
I see it's a common issue, somebody solved in this way:
https://github.com/thecodingmachine/docker-images-php/pull/139/commits/941219f03aec935e002bc19054dde1b5479c2c43

**Comment by Johannestegner** [comment]
Hi @fullbl! Thank you for the bug report.
This is a known issue (discussed shortly in #3) which I have been trying to fix for a while.

During my tests I have tried what you show in the php image as well as a while lot of other possible work-arounds, without it helping, but I'll take another round with it, as it _might_ have been an alpine issue (which there are new versions of now).

**Comment by Johannestegner** [comment]
So, a current work-around would be to run the container with a specific user:

`docker run -u 82 -v conf.cfg:/etc/lighttpd/conf.d/000-log.conf -p 80:80 jitesoft/lighttpd` 

although this is of course not optimal.

**Comment by fullbl** [comment]
Thank you for your answer! Actually running as user 82 works (also with docker compose), I feel the standard should be to run the non-root user and choosing it if needed... However the problem would be the opposite, right?
Personally I found the nginx solution pretty neat: https://github.com/nginxinc/docker-nginx/blob/8921999083def7ba43a06fabd5f80e4406651353/mainline/jessie/Dockerfile#L21-L23

**Comment by fullbl** [comment]
However, access logs seems to not be written when using `accesslog.filename = "/dev/stdout"` and user 82 (maybe I'm missing something, I'm not a frequent lighttpd user!). This is what I see:

```
xxx_ws.1.e0whqi9duwrj@full-PC    | Awaiting connection to CGI host
xxx_ws.1.e0whqi9duwrj@full-PC    | CGI host found, starting lighttpd!
xxx_ws.1.e0whqi9duwrj@full-PC    | 2022-12-12 08:46:13: (server.c.1588) server started (lighttpd/1.4.67)
xxx_ws.1.e0whqi9duwrj@full-PC    | 2022-12-12 08:46:13: (configfile.c.1287) WARNING: unknown config-key: dir-listing.activate (ignored)
xxx_ws.1.e0whqi9duwrj@full-PC    | 2022-12-12 08:51:02: (server.c.2097) server stopped by UID = 0 PID = 0
```

there is no entry for the http calls, which I'm sure are working, because there is the entry on the xxx_php container which handle the fastcgi data!

**Comment by Johannestegner** [comment]
Try to output to `/dev/fd/1` (stderr) and `/dev/fd/2` (stdout), the `/dev/stdout`.

**Comment by Johannestegner** [comment]
I also noticed that the healthcheck will create an entry in the access-log, which I'll try to find a good way to filter out :)

**Comment by fullbl** [comment]
Thank you, it works! 
I don't know if filtering healthchecks is good, what if the same method is used by an external healthcheck?

**Comment by Johannestegner** [comment]
Awesome :)

My initial thought about the healthcheck is to just add a user agent other than WGet, so that it can be easily filtered out. 
The filter would only apply to the access-log output too, which can be easily cluttered with internal calls. 
I'll think about it some more and see :)

When it comes to the user part, I'll as well have to think about it a bit and see what path I think is the best way to go, but I'm considering making the image use the correct user by default instead of root, as I really don't like the fact that it runs as root ;)

Will close this issue for now (seeing you got the logs to run with the "right" user), and update the image when I have tested it around a bit more and decided on the best path :)
