### ISSUE TITLE
[Q] - How to pass the env variable to config file?

### ISSUE THREAD

**Issue by hsiswantoro** [jitesoft/docker-lighttpd#6]
Hi, I really like your container and have been using it for a while.

I am wondering, how did you manage to pass the environment variables to the config files by just calling the variables name, for example: env.SERVER_ROOT, env.PORT, ... ? I have seen people did this through the entrypoint script, but  it's not in your case.

Thank you.

**Comment by Johannestegner** [comment]
Hi there!

Happy to hear that you enjoy the image! :)

Lighttpd supports usage of environment variables in the configuration file out of the box by using the `env.` directive.

I can't find the full documentation for it right now, but it's mentioned here in the variables section of the docs: https://redmine.lighttpd.net/projects/lighttpd/wiki/Docs_Configuration#Using-variables

**Comment by hsiswantoro** [comment]
I see, thank you!
